name: Deploy to Railway
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      COACH_WEBHOOK_SECRET: ${{ secrets.COACH_WEBHOOK_SECRET }}
      TZ: ${{ secrets.TZ }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh
      - name: Link Railway project
        run: railway link $RAILWAY_PROJECT_ID
      - name: Deploy to Railway
        run: railway up --project $RAILWAY_PROJECT_ID --detach
